#!/bin/bash
cd `dirname $0`
USER=$1

USERPATH=s3://$(get_bucket_name)/user/${USER}

status="0"
aws s3 ls ${USERPATH} && status="1"
if [ $status = "1" ]; then
  aws s3 cp ${USERPATH}/password -
else
  echo 'user not registered'
  exit 1
fi
