#!/bin/bash
cd `dirname $0`

FILEPATH=s3://$(get_bucket_name)/$1

status="0"
aws s3 ls ${FILEPATH} >/dev/null 2>&1 && status="1"
if [ $status = "1" ]; then
  aws s3 cp ${FILEPATH} -
else
  echo 'file not found'
  exit 1
fi
