#!/bin/bash
cd `dirname $0`

local_path="$(basedir)/$1"
local_dir="$(dirname $local_path)"
s3_path="s3://$(get_bucket_name)/$1"
if [ -e $local_path ]; then
  cat $local_path
  exit 0
fi

set -x

aws s3 cp $s3_path $local_path > /dev/null
if [ -e $local_path ]; then
  date +%s > $local_dir/CACHED
  cat $local_path
  exit 0
else
  echo "file not found" >&2
  exit 1
fi
