#!/bin/bash
cd `dirname $0`

local_path="$(basedir)/$1"
local_dir="$(dirname $local_path)"
s3_path="s3://$(get_bucket_name)/$1"
s3_dir="s3://$(get_bucket_name)/$(dirname $1)"
if [ -e $local_path ]; then
  cat $local_path
  exit 0
fi


file_found="0"
aws s3 cp --recursive $s3_dir $local_dir > /dev/null && file_found="1" 
if [ $file_found = "1" ]; then
  date +%s > $local_dir/CACHED
else
  echo "file not found" >&2
  exit 1
fi

if [ -e $local_path ]; then
  cat $local_path
  exit 0
fi

echo "file not found" >&2
exit 1
