#!/bin/bash
cd `dirname $0`

local_path="$(basedir)/$1"
local_dir="$(dirname $local_path)"
s3_path="s3://$(get_bucket_name)/$1"
s3_dir="s3://$(get_bucket_name)/$(dirname $1)"
if [ -e $local_path ]; then
  cat $local_path
  exit 0
fi

aws s3 cp --recursive $s3_dir $local_dir > /dev/null

if [ -e $local_path ]; then
  date +%s > $local_dir/CACHED
  cat $local_path
  exit 0
else
  if [ -z "$(ls $local_dir)" ]; then
    rm -r $local_dir
  fi
  echo "file not found" >&2
  exit 1
fi
