#!/bin/bash
cd `dirname $0`

FILEPATH=s3://$(get_bucket_name)/$1
local_path="$(basedir)/$1"
if [ -e $local_path ]; then
  cat $local_path
  exit 0
fi

status="0"
aws s3 ls ${FILEPATH} >/dev/null 2>&1 && status="1"
if [ $status = "1" ]; then
  aws s3 cp ${FILEPATH} -
else
  echo 'file not found'
  exit 1
fi
