#!/bin/bash
cd `dirname $0`

#set -x

local_path="$(basedir)/$1"
s3_path="s3://$(get_bucket_name)/$1"
if [ -e $local_path ]; then
  aws s3 cp $local_path $s3_path
  exit 0
else
  echo "file not found"
  exit 1
fi



